class CfgFontFamilies
{
	class VT323
	{
		fonts[] = {"x\addons\a3_epoch_configs\Data\Fonts\VT323\VT3236","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT3237","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT3238","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT3239","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32310","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32311","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32312","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32313","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32314","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32315","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32316","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32317","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32318","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32319","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32320","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32321","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32322","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32323","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32324","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32325","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32326","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32327","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32328","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32329","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32330","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32331","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32334","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32335","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32337","x\addons\a3_epoch_configs\Data\Fonts\VT323\VT32346"};
		spaceWidth = 0.7;
		spacing = 0.2;
	};
	class HVDPeace
	{
		fonts[] = {"x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace6","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace7","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace8","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace9","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace10","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace11","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace12","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace13","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace14","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace15","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace16","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace17","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace18","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace19","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace20","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace21","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace22","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace23","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace24","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace25","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace26","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace27","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace28","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace29","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace30","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace31","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace34","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace35","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace37","x\addons\a3_epoch_configs\Data\Fonts\HVDPeace\HVDPeace46"};
		spaceWidth = 0.7;
		spacing = 0.2;
	};
	class Millennia
	{
		fonts[] = {"x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia6","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia7","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia8","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia9","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia10","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia11","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia12","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia13","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia14","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia15","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia16","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia17","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia18","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia19","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia20","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia21","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia22","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia23","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia24","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia25","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia26","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia27","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia28","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia29","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia30","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia31","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia34","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia35","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia37","x\addons\a3_epoch_configs\Data\Fonts\Millennia\Millennia46"};
		spaceWidth = 0.7;
		spacing = 0.2;
	};
	class PolenticalNeon
	{
		fonts[] = {"x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon6","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon7","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon8","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon9","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon10","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon11","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon12","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon13","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon14","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon15","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon16","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon17","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon18","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon19","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon20","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon21","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon22","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon23","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon24","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon25","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon26","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon27","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon28","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon29","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon30","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon31","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon34","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon35","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon37","x\addons\a3_epoch_configs\Data\Fonts\PolenticalNeon\PolenticalNeon46"};
		spaceWidth = 0.7;
		spacing = 0.2;
	};
	class DJBGetDigital
	{
		fonts[] = {"x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital6","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital7","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital8","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital9","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital10","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital11","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital12","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital13","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital14","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital15","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital16","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital17","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital18","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital19","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital20","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital21","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital22","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital23","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital24","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital25","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital26","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital27","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital28","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital29","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital30","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital31","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital34","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital35","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital37","x\addons\a3_epoch_configs\Data\Fonts\DJBGetDigital\DJBGetDigital46"};
		spaceWidth = 0.7;
		spacing = 0.2;
	};
};
